name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
 test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.3']
        symfony: [ '6.4.*', '7.0.*', '7.1.*', '7.2.*']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, intl
          tools: composer:v2, flex

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        uses: ramsey/composer-install@v1

      - name: Run tests
        run: composer run test

 test-lowest:
    name: Test Lowest
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ['8.2', '8.3', '8.4']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, intl
          tools: composer:v2, flex

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test-lowest

 codestyle:
    name: Code style
    runs-on: ubuntu-latest
    container: jakzal/phpqa:php8.3
    steps:
      - uses: actions/checkout@v2
      - name: PHP CS Fixer (via jakzal/phpqa)
        run: php-cs-fixer fix -vv --dry-run

 static:
    name: Static code analysis
    runs-on: ubuntu-latest
    container: jakzal/phpqa
    steps:
      - uses: actions/checkout@v2
      - run: composer install
      - name: PHPStan (via jakzal/phpqa)
        run: phpstan analyze -c .phpstan.neon
